name: Infrastructure Deployment

on:
  push:
    branches:
      - main
    paths:
      - 'infrastructure-automation/**'
      - '.github/workflows/terraform-infra.yml' 
  workflow_dispatch:
    inputs:
      action:
        description: 'Terraform action'
        required: false
        default: 'apply'
        type: choice
        options:
        - plan
        - apply
        - destroy

run-name: "Infrastructure ${{ inputs.action || 'apply' }} by ${{ github.actor }}"

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: eu-central-1
      WORKING_DIRECTORY: infrastructure-automation
      TF_VERSION: 1.6.0

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: ${{ env.TF_VERSION }}

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Initialize Terraform
      working-directory: ${{ env.WORKING_DIRECTORY }}
      run: terraform init

    - name: Validate Terraform
      if: inputs.action != 'destroy'
      working-directory: ${{ env.WORKING_DIRECTORY }}
      run: terraform validate

    - name: Format Check
      if: inputs.action != 'destroy'
      working-directory: ${{ env.WORKING_DIRECTORY }}
      run: terraform fmt -check
      continue-on-error: true

    - name: Plan Terraform
      if: inputs.action != 'destroy'
      working-directory: ${{ env.WORKING_DIRECTORY }}
      run: terraform plan -out=tfplan

    - name: Apply Terraform
      if: inputs.action == 'apply' || github.event_name == 'push'
      working-directory: ${{ env.WORKING_DIRECTORY }}
      run: terraform apply -auto-approve tfplan

    - name: Destroy Terraform
      if: inputs.action == 'destroy'
      working-directory: ${{ env.WORKING_DIRECTORY }}
      run: terraform destroy -auto-approve

    - name: Output results
      if: inputs.action == 'apply' || github.event_name == 'push'
      working-directory: ${{ env.WORKING_DIRECTORY }}
      run: |
        echo "=== INFRASTRUCTURE OUTPUTS ==="
        echo "Application URL: $(terraform output -raw application_url)"
        echo "Load Balancer DNS: $(terraform output -raw load_balancer_dns_name)"
        echo "Database Endpoint: $(terraform output -raw database_endpoint)"
        echo "Secret ARN: $(terraform output -raw db_secret_arn)"
        echo "=========================="